site_name: Vet Clinic Booking System

theme:
  name: readthedocs

nav:
    - About: index.md 
    - Client Meeting Minutes: client_meeting_minutes.md
    - Project Management: project_management.md
    - Project Requirements: project_requirements.md
    - Software Design Requirements: software_design_requirements.md
    
